language: cpp

os:
  - linux
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

script:
  - make -j
  - python setup.py install

matrix:
  allow_failures:
    - os: osx


notifications:
  email:
    on_success: never
    on_failure: change
